### user signup endpoint
POST http://localhost:3000/v1/user
Content-Type: application/json

{
    "name":"Tharindu Perera",
    "id":"402134B",
    "division":"welfare",
    "position":"divison-officer",
    "phoneNumber":773679690,
    "email":"tharindu@uom.lk",
    "password":"qwerA1234"
}


### user signin endpoint
POST http://localhost:3000/v1/user/login
Content-Type: application/json

{
    "email":"vinu@uom.lk",
    "password":"qwerA1234"
    
}

### event creation endpoint
POST http://localhost:3000/v1/event
Content-Type: application/json

{
    "applicantName":"John Snow",
    "applicantIndex":"E56766",
    "faculty":"Engineering",
    "department":"Criminal Justice",
    "applicantEmail":"johnsnow@example.com",
    "phoneNumber":"45678901234",
    "placename":"Lecture Hall 1",
    "reasonofEvent":"Legal Ethics Workshop",
    "selectedDate":"2024-11-15T00:00:00Z",
    "startTime":"01:00 PM",
    "endTime":"05:00 PM"
}

### event fetch endpoint
GET http://localhost:3000/v1/event/e808d3a4-6b57-4153-800d-947b4585367a
Content-Type: application/json




