### user signup endpoint
POST http://localhost:3000/v1/user
Content-Type: application/json

{
    "name":"Tharindu Perera",
    "id":"402134B",
    "division":"welfare",
    "position":"divison-officer",
    "phoneNumber":773679690,
    "email":"tharindu@uom.lk",
    "password":"qwerA1234"
}


### user signin endpoint
POST http://localhost:3000/v1/user/login
Content-Type: application/json

{
    "email":"vinu@uom.lk",
    "password":"qwerA1234"
    
}

### event creation endpoint
POST http://localhost:3000/v1/event
Content-Type: application/json

{
    "applicantName":"Wiil Smith",
        "applicantIndex":"E99183",
        "faculty":"Engineering",
        "department":"Criminal Justice",
        "applicantEmail":"johnsnow1@example.com",
        "phoneNumber":"45678908052",
        "placename":"Lecture Hall 3",
        "reasonofEvent":"Legal Ethics Workshop",
        "selectedDate":"2024-08-05T11:06:34Z",
        "startTime":"03:00 PM",
        "endTime":"06:00 PM"
}

### event fetch endpoint
GET http://localhost:3000/v1/event/7aab8373-0c84-47e3-ac06-12d8a60c489a
Content-Type: application/json

### close event endpoint
PATCH http://localhost:3000/v1/event/7a8abcf4-75fe-4645-aa60-a1ea156f31b7
Content-Type: application/json

{
    "status":"closed"
}




